name: Danger

on:
  pull_request:
    branches: [ main ]

jobs:
  danger:
    name: 'Danger'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
    - name: Set up Node
      uses: actions/setup-node@v1
    - uses: actions/cache@v2.1.7
      with:
        path: |
          vendor/bundle
          ~/.cache/pip
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
        python -m pip install --upgrade pip
        pip install proselint
        npm i markdown-spellcheck -g
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
